// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSwqfVD_bpecq3YrpOimZgpsCKkmbePo',
    appId: '1:770895781782:web:ce563907e78597f2d187b7',
    messagingSenderId: '770895781782',
    projectId: 'zetzero-1ad01',
    authDomain: 'zetzero-1ad01.firebaseapp.com',
    storageBucket: 'zetzero-1ad01.firebasestorage.app',
    measurementId: 'G-TZ21QRFESN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfeawm5fklFs9NdTOG3PrnO61PhFPNhM',
    appId: '1:770895781782:android:98a9bb162a7bb33ad187b7',
    messagingSenderId: '770895781782',
    projectId: 'zetzero-1ad01',
    storageBucket: 'zetzero-1ad01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPtstE20FIrgEQB7DxqB7KPPYg9qAJxy4',
    appId: '1:770895781782:ios:bbe7a5edb55e2986d187b7',
    messagingSenderId: '770895781782',
    projectId: 'zetzero-1ad01',
    storageBucket: 'zetzero-1ad01.firebasestorage.app',
    iosClientId: '770895781782-cop6d2g3iks55gujmk9kbqa9vflcd2db.apps.googleusercontent.com',
    iosBundleId: 'com.example.zetZero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSwqfVD_bpecq3YrpOimZgpsCKkmbePo',
    appId: '1:770895781782:web:15b655c89e357438d187b7',
    messagingSenderId: '770895781782',
    projectId: 'zetzero-1ad01',
    authDomain: 'zetzero-1ad01.firebaseapp.com',
    storageBucket: 'zetzero-1ad01.firebasestorage.app',
    measurementId: 'G-32GDPRCSM8',
  );
}
